---
# Install Couchbase server

- name: Download Couchbase pkg
  get_url: url={{ pkg_src }} dest=~/{{ pkg_name }}

- name: Install Couchbase .deb file
  shell: dpkg -i ~/{{ pkg_name }}

- name: Initialize cluster
  shell: /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username={{ user }} --cluster-init-password={{ password }} --cluster-init-ramsize={{ ramsize }}

- name: Create bucket
  shell: /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket={{ bucket_name }} --bucket-type={{ bucket_type }} --bucket-port={{ bucket_port }} --bucket-ramsize={{ bucket_ramsize }} --bucket-replica=0 -u {{ user }} -p {{ password }}

