---
# Update the server and install some tools

- apt: update_cache=yes
- apt: upgrade=yes

- name: Set correct timezone 
  shell: echo {{ timezone }} > /etc/timezone

- name: Reconfigure tzdata
  command: dpkg-reconfigure -f noninteractive tzdata

- apt: pkg={{ item }} state=present
  with_items:
    - htop
    - iftop

- lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1' line='127.0.1.1 {{ hostname }}'

- lineinfile: dest=/etc/hostname regexp='^.' line="{{ hostname }}"

